language: python
python:
- 3.8
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: eem/9Bq9EV9AAFo09n8PcUQsD2MznwnXnzuGM9zfOyqNmTklw9ngueF0o45wQX496aDL4KLTrkpaYfXzSbjtkSz9fxn+WWlUf7U5/GQaB+JaF6OITv4XAvt1GxWvXIsRHOdvaliSy1TOx/TVvuarCCH9Dk5YlJpM79hVSKzar5IwwW/4YQ1/Nt6vTPcROkV/esR0JjZmYrwPXkAXiQiZMZl3FzZWgK8vrnAix4JzyZaZ35z2xkvOcWpQH070kn5b6s1dYhootB6GCnmkXzqU5i2nU725vzUfUYzRZm7FW2NfOMDoO0RFk/sGjl9HT9ZbhIkXTgBWx7uYNnVjgya7YdkBdRie3nm5b9HO6xT+nsTh49T6oH98eFyEE/9kNynl0gCxaqTy9tmQjL0EcXoumYq/Uh3CRzoj8A1zh+aCwgwBRoPBTz5IOFUuzKmV9z8ZSH1tl+m+Rd/QB1Yo/1+JhvETh2tKX1jXL8UHMPJmPARttlU9Rd7AtZG6u4PI0xrmaGSicGH0Cmp+YqMPzIyMFZctRQ1q63cQRELDEA35XVwmmsUixOqwAAlymrJJUj1Ewil7oiSM+UuUysx8vYnrLGnjQwdQwCjSxEP2rfnbLOx9dPqH++P0w603bqArSk/CWUyYLW7AQahQZkA9lLQqy1+gTII7Q0PQzJiK6fIqW3U=
  on:
    tags: true
    repo: cdumay/cdumay-result
